####restufull api for mongodb crud operation

@baseurl = http://localhost:8000/api/v1/task
POST {{baseurl}}
Content-Type: application/json

{
  "name":"shelhar",
  "mdfhfj":"mehladsfhtjky"
}



###
GET {{baseurl}}


###
PATCH  {{baseurl}}
Content-Type: application/json

{
  "_id": "66b58df7ad5a3c597c835309",
    "name": "updatethis"
}

###
PUT  {{baseurl}}
Content-Type: application/json

{
  "_id": "66b58df7ad5a3c597c835309",
    "hell0":"djfrjsd"
}



